spring.application.name=CodeGallery

spring.datasource.url=jdbc:mysql://localhost:3306/selenium_tutorials?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=always
spring.sql.init.schema-locations=file:./database/schema.sql
spring.jpa.defer-datasource-initialization=true
